version: 0.2

phases:
  install:
    commands:
      - cd backend && npm i && cd ..
      - cd web && npm i && cd ..
      - cd tools && npm i && cd ..
  build:
    commands:
      - cd backend && npm run build:dev && cd ..
      - cd tools && npm run pack:bundle && cd ..
artifacts:
  files:
    - tools/scripts/aws/help-educate@1.0.0.zip
    discard-paths: yes
    base-directory: tools/scripts/aws

